version: '3.8'
services:

  inscriptionrabbitmq:
    build:
      context: ./.
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - MYSQL_URL=jdbc:mysql://mysqlserver/inscriptionbdd
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=inscriptionbdd
      - MYSQL_PASSWORD=ynov
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=ynov
    ports:
      - 3306

networks:
  default:
    name: rabbitmq_network
    external: true